import type { Metadata } from "next";
import { Raleway, Oswald } from "next/font/google";
import "./globals.css";
import Providers, { ConnectKitButton } from "./Providers";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  display: "swap",
});
const oswald = Oswald({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${oswald.variable} ${raleway.className}`}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}

import Image from "next/image";
import Link from "next/link";
import LogoImage from "../../public/logo.png";
import { IoMenuSharp } from "react-icons/io5";

const Header = () => {
  return (
    <header className="pl-4 md:px-8 lg:px-12 py-6 sticky top-0 bg-base-100 z-30 font-oswald">
      <nav className="flex flex-row justify-between items-center">
        <Image src={LogoImage} alt="Lynx Tech Logo" width={50} height={50} />
        <a
          href="https://lynxtech.io/"
          className="md:text-base text-xl font-medium hover:text-primary hidden md:block"
        >
          Home
        </a>
        <a
          href="https://lynxtech.io/index.php/deadshot/"
          className="md:text-base text-xl font-medium hover:text-primary hidden md:block"
        >
          DeadShot
        </a>
        <Link
          href="/"
          className="md:text-base text-xl font-medium hover:text-primary hidden md:block"
        >
          Staking
        </Link>
        <a
          href="https://lynxtech.io/index.php/lynx/"
          className="md:text-base text-xl font-medium hover:text-primary hidden md:block"
        >
          $LYNX
        </a>
        <a
          href="https://lynxtech.io/lynxtechwp.pdf"
          className="md:text-base text-xl font-medium hover:text-primary hidden md:block"
        >
          Whitepaper
        </a>
        <div className="hidden md:block">
          <ConnectKitButton />
        </div>
        <div className="dropdown dropdown-end md:hidden">
          <div className="pr-4">
            <label tabIndex={0} className="btn btn-primary">
              <IoMenuSharp className="text-2xl" />
            </label>
          </div>
          <div className="dropdown-content shadow w-screen">
            <nav className="flex flex-col items-center gap-2 bg-accent-background pb-4 rounded-b-2xl">
              <a
                href="https://lynxtech.io/"
                className="text-lg py-2 font-medium hover:text-white text-center hover:bg-secondary w-full"
              >
                Home
              </a>
              <a
                href="https://lynxtech.io/index.php/deadshot/"
                className="text-lg py-2 font-medium hover:text-white text-center hover:bg-secondary w-full"
              >
                Deadshot
              </a>
              <Link
                href="/"
                className="text-lg py-2 font-medium hover:text-white text-center hover:bg-secondary w-full"
              >
                Reward
              </Link>
              <a
                href="https://lynxtech.io/index.php/lynx/"
                className="text-lg py-2 font-medium hover:text-white text-center hover:bg-secondary w-full"
              >
                $LYNX
              </a>
              <a
                href="https://lynxtech.io/lynxtechwp.pdf"
                className="text-lg py-2 font-medium hover:text-white text-center hover:bg-secondary w-full"
              >
                Whitepaper
              </a>
              <ConnectKitButton />
            </nav>
          </div>
        </div>
      </nav>
    </header>
  );
};
